name: Docker CD

on:
  push:
    branches: 
      - master

jobs:
  build-backend:
    runs-on: ubuntu-latest   
    env:
        DOCKER_PASS: ${{ secrets.HUB_PASSWORD }}
        IMAGE: theleede/cdnder-backend 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        
        run: |
          docker build -t ${IMAGE} . \
            -f backend/Dockerfile
          docker tag ${IMAGE} ${IMAGE}:latest
          docker tag ${IMAGE} ${IMAGE}:${GITHUB_SHA::8}
      - name: Push Image
        run: |
          docker login -u theleede -p ${DOCKER_PASS}
          docker push ${IMAGE}
          
  build-frontend:
    runs-on: ubuntu-latest   
    env:
        DOCKER_PASS: ${{ secrets.HUB_PASSWORD }}
        IMAGE: theleede/cdnder-frontend 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        
        run: |
          docker build -t ${IMAGE}  \
            ./web
          docker tag ${IMAGE} ${IMAGE}:latest
          docker tag ${IMAGE} ${IMAGE}:${GITHUB_SHA::8}
      - name: Push Image
        run: |
          docker login -u theleede -p ${DOCKER_PASS}
          docker push ${IMAGE}